import { LeadSourceType } from '@prisma/client';
import type { CapturedLeadInput } from '../leads/leads.service';

export const captureFixtures: CapturedLeadInput[] = [
  {
    displayName: 'Arpoador Sunset',
    rawPhone: '(21) 98765-4432',
    whatsapp: '5521987654432',
    instagram: '@arpoadorsunset',
    city: 'Rio de Janeiro',
    state: 'RJ',
    leadCategory: 'Label de festas',
    eventType: 'Sunset',
    sourceType: LeadSourceType.GOOGLE_SEARCH,
    sourceLabel: 'Google Search',
    sourceUrl: 'https://arpoadorsunset.com/contato',
    confidence: 82,
    eventSignals: ['sunset', 'lote', 'line-up', 'evento'],
    payload: {
      seeded: true,
      captureOrigin: 'google-search',
    },
  },
  {
    displayName: 'Arpoador Sunset',
    rawPhone: '(21) 98765-4432',
    whatsapp: '5521987654432',
    city: 'Rio de Janeiro',
    state: 'RJ',
    leadCategory: 'Label de festas',
    eventType: 'Sunset',
    sourceType: LeadSourceType.TICKETING_SITE,
    sourceLabel: 'Bilheteria online',
    sourceUrl: 'https://ticket.example/arpoador-sunset',
    confidence: 88,
    eventSignals: ['sunset', 'open bar', 'evento'],
    payload: {
      seeded: true,
      captureOrigin: 'ticketing',
    },
  },
  {
    displayName: 'Rep Festa Prime',
    rawPhone: '(31) 99120-5566',
    city: 'Belo Horizonte',
    state: 'MG',
    leadCategory: 'Republica',
    eventType: 'Universitario',
    sourceType: LeadSourceType.MANUAL_WEBSITE,
    sourceLabel: 'Landing page universitaria',
    sourceUrl: 'https://repfestaprime.com.br',
    confidence: 76,
    eventSignals: ['festa', 'universitario', 'atlética'],
    payload: {
      seeded: true,
      captureOrigin: 'landing-page',
    },
  },
  {
    displayName: 'Secretaria de Eventos de Ribeirao',
    rawPhone: '(16) 99222-1000',
    city: 'Ribeirao Preto',
    state: 'SP',
    leadCategory: 'Evento de prefeitura',
    eventType: 'Show',
    sourceType: LeadSourceType.PUBLIC_REGISTRY,
    sourceLabel: 'Portal da prefeitura',
    sourceUrl: 'https://prefeitura.example.gov.br/eventos',
    confidence: 85,
    eventSignals: ['prefeitura', 'agenda', 'show'],
    payload: {
      seeded: true,
      captureOrigin: 'public-registry',
    },
  },
];
